const UserActionTypes = {
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    EMAIL_LOG_IN_START: 'EMAIL_LOG_IN_START',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    LOG_OUT_START: 'LOG_OUT_START',
    LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
    LOG_OUT_FAILURE: 'LOG_OUT_FAILURE',
}

export default UserActionTypes;