
const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    CHANGE_CART_ITEM_ATTRIBUTE: 'CHANGE_CART_ITEM_ATTRIBUTE'
}

export default CartActionTypes