
const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREMENT_ITEM: 'INCREMENT_ITEM',
    DECREMENT_ITEM: 'DECREMENT_ITEM',
    CHECK_CART_SESSION_STORAGE: 'CHECK_CART_SESSION_STORAGE',
    RETRIEVE_CART_SESSION_STORAGE: 'RETRIEVE_CART_SESSION_STORAGE'
}

export default CartActionTypes