const OrderActionTypes = {
    ORDER_PAYMENT_START: 'ORDER_PAYMENT_START',
    ORDER_PAYMENT_SUCCESS: 'ORDER_PAYMENT_SUCCESS',
    ORDER_PAYMENT_FAILURE: 'ORDER_PAYMENT_FAILURE',
}

export default OrderActionTypes;