const ShopActionTypes = {
    FETCH_INITIAL_SHOP_PRODUCTS_START: 'FETCH_INITIAL_SHOP_PRODUCTS_START',
    FETCH_INITIAL_SHOP_PRODUCTS_SUCCESS: 'FETCH_INITIAL_SHOP_PRODUCTS_SUCCESS',
    FETCH_INITIAL_SHOP_PRODUCTS_FAILURE: 'FETCH_INITIAL_SHOP_PRODUCTS_FAILURE'
}

export default ShopActionTypes;