const ShopActionTypes = {
    FETCH_INITIAL_SHOP_PRODUCTS_START: 'FETCH_INITIAL_SHOP_PRODUCTS_START',
    FETCH_INITIAL_SHOP_PRODUCTS_SUCCESS: 'FETCH_INITIAL_SHOP_PRODUCTS_SUCCESS',
    FETCH_INITIAL_SHOP_PRODUCTS_FAILURE: 'FETCH_INITIAL_SHOP_PRODUCTS_FAILURE',
    FETCH_FILTERED_SHOP_PRODUCTS_START: 'FETCH_FILTERED_SHOP_PRODUCTS_START',
    FETCH_FILTERED_SHOP_PRODUCTS_SUCCESS: 'FETCH_FILTERED_SHOP_PRODUCTS_SUCCESS',
    FETCH_FILTERED_SHOP_PRODUCTS_FAILURE: 'FETCH_FILTERED_SHOP_PRODUCTS_FAILURE',
    CLEAR_SHOP_FILTER: 'CLEAR_SHOP_FILTER',
    CHANGE_CURRENTLY_VIEWED_PRODUCT: 'CHANGE_CURRENTLY_VIEWED_PRODUCT',
    FETCH_PRODUCT_DATA_START: 'FETCH_PRODUCT_DATA_START',
    FETCH_PRODUCT_DATA_SUCCESS: 'FETCH_PRODUCT_DATA_SUCCESS',
    FETCH_PRODUCT_DATA_FAILURE: 'FETCH_PRODUCT_DATA_FAILURE'
}

export default ShopActionTypes;